# Generated by Django 5.2.6 on 2025-11-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
