# Generated by Django 5.2.6 on 2025-11-23 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_opened_page', models.CharField(blank=True, max_length=200)),
                ('completed_lessons', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('selected_guitar_type', models.CharField(blank=True, max_length=50)),
                ('page_theme', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
